server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/umc
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    p6spy: INFO
    org.umc.spring.monitoring: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    enable:
      jvm: true
      hikaricp: true
      hibernate: true
      system: true
      process: true
    export:
      prometheus:
        enabled: true
    tags:
      application: umc-8th-server
      environment: staging

monitoring:
  slow-query:
    threshold: 1000    # 쿼리 실행 시간이 1초를 넘으면 슬로우 쿼리로 간주
    alert-enabled: true
  database:
    connection-pool:
      alert-threshold: 80   # 커넥션 풀 사용률이 80% 이상 시 알림