server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/umc
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    p6spy: INFO